
server:
  port: 8081
  context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript
  tomcat:
    uri-encoding: UTF-8